version: '2'

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.10.10.0/24

services:

  nodejs:
    container_name: nodejs
    build:
      context: nodejs
    image: nodejs
    ports:
      - 3000:3000
      - 4000:4000
    entrypoint: sleep 99999999999
    volumes:
      - .:/app
    networks:
      app_net:
        ipv4_address: 10.10.10.11
  mariadb:
    container_name: mariadb
    build:
      context: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      app_net:
        ipv4_address: 10.10.10.12

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      app_net:
        ipv4_address: 10.10.10.13
